// <auto-generated />
namespace RoboboKitchenProject.DAL.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mgr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mgr));
        
        string IMigrationMetadata.Id
        {
            get { return "202005281659558_mgr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
