// <auto-generated />
namespace RoboboKitchenProject.DAL.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mgrDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mgrDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202005282241356_mgrDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
